openapi: 3.0.1
info:
  description: ApiCartoon
  version: 3.0.0
  title: CartoonAPI
  contact:
    email: egofernandez91@gmail.com
    name: Eduardo Gomez Fernandez


servers:
  - url: http://localhost:8080/

paths:
    /cartoons:
      $ref: './api/cartoon.api.yaml#/cartoons'













